<?php
/** @var \App\Model\User $user */
$user = $this->user;
?>

<?php if($user): ?>
    Редактировать:
    <form action="/user/edit/" method="post">

        Имя: <input type="text" name="name" value="<?= $user->getName();?>"> <br>
        Email: <input type="text" name="email" value="<?= $user->getEmail();?>"> <br>
        Пароль: <input type="password" name="password"> <br>
        Повторите пароль: <input type="password" name="password2"> <br>
        <input type="submit" value="Сохранить">
    </form>
    <form action="/user/profile">
        <input type="submit" value="Вернуться в профиль">
    </form>

<?php else: ?>
    Пользователь не найден
<?php endif; ?>

<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?></span>
<?php endif; ?>



